name: clean_data
version: 0.3.6
author: Clean Team <clean@vacuumlabs.com>
description: Support for automatical data synchronization among collections.
homepage: http://cleandart.github.io/clean_data/
documentation: http://cleandart.github.io/clean_data/
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dev_dependencies:
  hop: any
  unittest: any
